name: Build femboyOS

on:
  workflow_dispatch:

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GHT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file buildenv/Dockerfile --tag femboyos:buildenv

    - name: Compile femboyOS
      run: docker run --rm -v ${{ github.workspace }}:/root/env femboyos:buildenv make build-x86_64

    - name: Make release
      uses: softprops/action-gh-release@v2.1.0
      with:
        tag_name: "build-${{ github.sha }}"
        name: "femboyOS Build from Commit ${{ github.sha }}"
        body: |
          This release was built from commit `${{ github.sha }}`.
          View the changes here: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        files: |
          dist/x86_64/femboyOS.bin
          dist/x86_64/femboyOS.iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
