name: Build femboyOS

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file buildenv/Dockerfile --tag femboyos:buildenv

    - name: Compile femboyOS
      run: docker run --rm -v $(pwd):/root/env femboyos:buildenv make build-x86_64

    - name: Make release
      uses: softprops/action-gh-release@v2.1.0
      with:
        tag_name: "v1.0 ALPHA"
        name: "femboyOS v1.0 ALPHA"
        files: |
          dist/kernel.bin
          dist/kernel.iso
