name: Build and Release femboyOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-x86_64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull the Buildenv Docker image
      run: docker pull ghcr.io/${{ github.repository_owner }}/femboyos-buildenv:latest

    - name: Compile femboyOS
      run: docker run --rm -v ${{ github.workspace }}:/root/env ghcr.io/${{ github.repository_owner }}/femboyos-buildenv:latest make build-x86_64

    - name: Chown dist dir
      run: sudo chown -R $USER:$USER dist
      
    - name: Compile Hashes
      run: |
        sha256sum dist/x86_64/femboyOS.iso > dist/x86_64/sha256sums.txt
        sha256sum dist/x86_64/femboyOS.bin >> dist/x86_64/sha256sums.txt

    - name: Make release
      uses: softprops/action-gh-release@v2.1.0
      with:
        tag_name: "build-${{ github.sha }}"
        name: "femboyOS Build from Commit ${{ github.sha }}"
        body: |
          This release was built from commit `${{ github.sha }}`.
          View the changes here: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        files: |
          dist/x86_64/femboyOS.bin
          dist/x86_64/femboyOS.iso
          dist/x86_64/sha256sums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}