name: CI

on: [
    pull_request
]

jobs:
    build-x86_64:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Pull the Buildenv Docker image
              run: docker pull ghcr.io/${{ github.repository_owner }}/femboyos-buildenv:latest

            - name: Compile femboyOS
              run: docker run --rm -v ${{ github.workspace }}:/root/env ghcr.io/${{ github.repository_owner }}/femboyos-buildenv:latest make build-x86_64
