name: Close PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened] 

jobs:
    close_prs:
        runs-on: ubuntu-latest
        steps:
            - name: Close PRs
              uses: actions/github-script@v6
              with:
                script: |
                    const blockedUsers = ['coolbeans1212'];

                    const actor = context.payload.sender.login;

                    if (blockedUsers.includes(actor)) {
                      const isPR = !!context.payload.pull_request;

                      if (isPR) {
                        // Close the pull request
                        await github.rest.pulls.update({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.payload.pull_request.number,
                          state: 'closed'
                        });

                        // Comment on the pull request
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.payload.pull_request.number,
                          body: 'This pull request has been automatically closed. Contributions from this user are not permitted.'
                        });

                      } else {
                        // Close the issue
                        await github.rest.issues.update({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.payload.issue.number,
                          state: 'closed'
                        });

                        // Comment on the issue
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.payload.issue.number,
                          body: 'This issue has been automatically closed. Contributions from this user are not permitted.'
                        });
                      }
                    }