name: Close PRs

on:
  pull_request:
    types: [opened]

jobs:
    close_prs:
        runs-on: ubuntu-latest
        steps:
            - name: Close PRs
              uses: actions/github-script@v6
              with:
                script: |
                    const blockedUsers = ['coolbeans1212'];
                    if (blockedUsers.includes(context.payload.pull_request.user.login)) {
                    await github.rest.pulls.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.payload.pull_request.number,
                        state: 'closed'
                    });

                    await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.pull_request.number,
                        body: 'This PR has been automatically closed because the user is not allowed to contribute.'
                    });
                    }
                    else {
                        console.log('User is allowed to contribute. No action taken.');
                    }