name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: GHCR-Action
      uses: KuhlTime/ghcr-action@v2
      with:
        token: secrets.GITHUB_TOKEN
        dockerfile: buildenv/Dockerfile
        image-name-overwrite: femboyos:buildenv
